/**
 * OTP (One-Time Password) entity matching the database schema.
 * Used for email verification and password reset.
 */
export class OtpEntity {
  constructor(
    public readonly id: string,
    public readonly userId: string,
    public readonly code: string,
    public readonly expiresAt: Date,
    public readonly createdAt: Date,
  ) {}

  /**
   * Creates a new OTP entity.
   */
  static create(props: {
    userId: string;
    code: string;
    expiryMinutes?: number;
  }): OtpEntity {
    const now = new Date();
    const expiresAt = new Date(now);
    expiresAt.setMinutes(expiresAt.getMinutes() + (props.expiryMinutes ?? 10)); // Default 10 minutes

    return new OtpEntity(
      '', // ID will be generated by database
      props.userId,
      props.code,
      expiresAt,
      now,
    );
  }

  /**
   * Checks if the OTP has expired.
   */
  isExpired(): boolean {
    return new Date() > this.expiresAt;
  }
}
