export class PersonalityArchetypeEntity {
  constructor(
    public readonly id: number,
    public readonly name: string,
    public readonly description: string,
    public readonly traits: string[],
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly imageUrl: string | null = null,
  ) {}

  static create(props: {
    name: string;
    description: string;
    traits: string[];
    imageUrl?: string | null;
  }): PersonalityArchetypeEntity {
    const now = new Date();
    return new PersonalityArchetypeEntity(
      0, // ID generated by DB/Auto-increment
      props.name,
      props.description,
      props.traits,
      now,
      now,
      props.imageUrl ?? null,
    );
  }
}
