export class QuestionnaireQuestionEntity {
  constructor(
    public readonly id: string,
    public readonly text: string,
    public readonly order: number,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}
}

export class QuestionnaireOptionEntity {
  constructor(
    public readonly id: string,
    public readonly questionId: string,
    public readonly text: string,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}
}

export class UserQuestionnaireAnswerEntity {
  constructor(
    public readonly id: string,
    public readonly profileId: number,
    public readonly questionId: string,
    public readonly selectedOptionId: string,
    public readonly createdAt: Date,
  ) {}

  static create(props: {
    profileId: number;
    questionId: string;
    selectedOptionId: string;
  }): UserQuestionnaireAnswerEntity {
    return new UserQuestionnaireAnswerEntity(
      '', // ID generated by DB
      props.profileId,
      props.questionId,
      props.selectedOptionId,
      new Date(),
    );
  }
}
