/**
 * Session entity matching the database schema.
 * Stores refresh tokens for user authentication.
 */
export class SessionEntity {
  constructor(
    public readonly id: string,
    public readonly userId: string,
    public readonly refreshToken: string,
    public readonly expiresAt: Date,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly deletedAt: Date | null,
  ) {}

  /**
   * Creates a new session entity.
   */
  static create(props: {
    userId: string;
    refreshToken: string;
    expiresInDays?: number;
  }): SessionEntity {
    const now = new Date();
    const expiresAt = new Date(now);
    expiresAt.setDate(expiresAt.getDate() + (props.expiresInDays ?? 7)); // Default 7 days

    return new SessionEntity(
      '', // ID will be generated by database
      props.userId,
      props.refreshToken,
      expiresAt,
      now,
      now,
      null, // Not deleted
    );
  }

  /**
   * Checks if the session has expired.
   */
  isExpired(): boolean {
    return new Date() > this.expiresAt;
  }

  /**
   * Checks if the session is active (not deleted and not expired).
   */
  isActive(): boolean {
    return this.deletedAt === null && !this.isExpired();
  }
}
