/**
 * User roles for authorization.
 */
export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
}

/**
 * Account status names matching the database enum.
 */
export enum AccountStatusName {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
}

/**
 * Account status entity.
 */
export class AccountStatusEntity {
  constructor(
    public readonly id: string,
    public readonly name: AccountStatusName,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}
}

/**
 * User entity matching the database schema.
 */
export class UserEntity {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly passwordHash: string,
    public readonly accountStatusId: string,
    public readonly isVerified: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly deletedAt: Date | null,
  ) {}

  /**
   * Creates a new user entity with default values.
   */
  static create(props: {
    email: string;
    passwordHash: string;
    accountStatusId?: string;
    isVerified?: boolean;
  }): UserEntity {
    const now = new Date();
    return new UserEntity(
      '', // ID will be generated by database
      props.email.toLowerCase(),
      props.passwordHash,
      props.accountStatusId ?? '', // Should be set to PENDING status ID
      props.isVerified ?? false,
      now,
      now,
      null, // Not deleted
    );
  }

  /**
   * Checks if the user account is active.
   */
  isActive(): boolean {
    return this.deletedAt === null;
  }
}
