/**
 * User roles for authorization.
 */
export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
  MODERATOR = 'moderator',
}

/**
 * Account status names matching the database enum.
 */
export enum AccountStatusName {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
}

/**
 * Account status entity.
 */
export class AccountStatusEntity {
  constructor(
    public readonly id: number,
    public readonly name: AccountStatusName,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}
}

/**
 * User entity matching the database schema.
 */
export class UserEntity {
  constructor(
    public readonly id: string,
    public readonly email: string,
    public readonly passwordHash: string,
    public readonly accountStatusId: number,
    public readonly role: UserRole,
    public readonly isVerified: boolean,
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
    public readonly deletedAt: Date | null,
    public readonly recoveryEmail: string | null = null,
    public readonly userId: string = '',
  ) {}

  /**
   * Generates a random 8-digit string of digits.
   */
  static generateRandomUserId(): string {
    let result = '';
    for (let i = 0; i < 8; i++) {
      result += Math.floor(Math.random() * 10).toString();
    }
    return result;
  }

  /**
   * Creates a new user entity with default values.
   */
  static create(props: {
    email: string;
    passwordHash: string;
    userId?: string;
    accountStatusId?: number;
    role?: UserRole;
    isVerified?: boolean;
    recoveryEmail?: string | null;
  }): UserEntity {
    const now = new Date();
    return new UserEntity(
      '', // ID will be generated by database
      props.email.toLowerCase(),
      props.passwordHash,
      props.accountStatusId ?? 1, // Default PENDING ID (integer 1)
      props.role ?? UserRole.USER,
      props.isVerified ?? false,
      now,
      now,
      null, // Not deleted
      props.recoveryEmail ? props.recoveryEmail.toLowerCase() : null,
      props.userId ?? this.generateRandomUserId(),
    );
  }

  /**
   * Checks if the user account is active.
   */
  isActive(): boolean {
    return this.deletedAt === null;
  }
}
